partner:
    type: group
    route: /partners
    routes: 
        #list:
        #    route: ~
        #    controller: PartnerController
        #    method: list
        new: 
            route: /new
            controller: Admin:PartnerController
            method: new
        new_contract: 
            route: /{partner:int}/new_contract
            controller: Admin:PartnerController
            method: newContract
        edit: 
            route: /{partner:int}/edit
            controller: Admin:PartnerController
            method: edit