farmer:
    type: group
    route: /farmer
    component: Farmer
    routes:
        overview:
            route: /
            use: Farmer::FarmerController:overview
        edit_self:
            route: /edit
            use: Farmer::FarmerController:edit

trade:
    type: group
    route: /trade
    component: Farmer
    routes:
        delete_trade:
            route: /{trade:int}/delete
            use: Farmer::TradeController:delete
        purchase_trade:
            route: /{trade:int}/purchase
            use: Farmer::TradeController:purchaseTrade