farmer:
    type: group
    route: /farmer
    component: Farmer
    routes:
        overview:
            route: /
            controller: Farmer:FarmerController
            method: overview
        edit_self:
            route: /edit
            controller: Farmer:FarmerController
            method: edit

trade:
    type: group
    route: /trade
    component: Farmer
    routes:
        delete_trade:
            route: /{trade:int}/delete
            controller: Farmer:TradeController
            method: delete
        purchase_trade:
            route: /{trade:int}/purchase
            controller: Farmer:TradeController
            method: purchaseTrade