partner:
    type: group
    route: /partners
    routes: 
        new: 
            route: /new
            controller: Admin:PartnerController
            method: new
        new_contract: 
            route: /{partner:int}/new_contract
            controller: Admin:PartnerController
            method: newContract
        edit: 
            route: /{partner:int}/edit
            controller: Admin:PartnerController
            method: edit

admin:
    type: group
    route: /admin
    component: Admin
    routes:
        manage_cache:
            route: /cache
            controller: Admin:AdminController
            method: manageCache
        invalidate_cache:
            route: /cache/invalidate/
            controller: Admin:AdminController
            method: invalidateCache
            methods: [post]