partner:
    type: group
    route: /partners
    routes: 
        new: 
            route: /new
            use: Admin::PartnerController:new
        new_contract: 
            route: /{partner:int}/new_contract
            use: Admin::PartnerController:newContract
        edit:
            route: /{partner:int}/edit
            use: Admin::PartnerController:edit
admin:
    type: group
    route: /admin
    component: Admin
    routes:
        manage_cache:
            route: /cache
            use: Admin::AdminController:manageCache
        invalidate_cache:
            route: /cache/invalidate/
            use: Admin::AdminController:invalidateCache
            methods: [POST]
        test:
            route: /test
            use: Admin::AdminController:test