api:
    type: group
    route: /api
    routes: 
        sync:
            route: /sync
            controller: APIController
            method: sync
            methods: [get,post]
        new_trade:
            route: /trade/new
            controller: API:TradeController
            method: new
        trade_overview:
            route: /trade/{trade:int}
            controller: API:TradeController
            method: overview
        farmer_overview:
            route: /farmer/{farmer:text}/overview
            controller: API:FarmerController
            method: overview
        farmers:
            route: /farmers
            controller: API:FarmerController
            method: getFarmers
        contracts:
            route: /contracts
            controller: API:ContractController
            method: list
        contract_overview:
            route: /contract/{contract:int}
            controller: API:ContractController
            method: overview
        fulfill_contract:
            route: /contract/{contract:int}/fulfill
            controller: API:ContractController
            method: fulfill
            methods: [POST]


