api:
    type: group
    route: /api
    routes: 
        sync:
            route: /sync
            use: API::APIController:sync
            check: checkIsAuthenticated
        new_trade:
            route: /trade/new
            use: API::TradeController:new
            check: checkIsAuthenticated
            methods: [GET,POST]
        trade_overview:
            route: /trade/{trade:int}
            use: API::TradeController:overview
        farmer_overview:
            route: /farmer/{farmer:text}
            use: API::FarmerController:overview
        farmers:
            route: /farmers
            use: API::APIController:list
        partner_overview:
            route: /partner/{partner:int}
            use: API::PartnerController:overview
        contracts:
            route: /contracts
            use: API::ContractController:list
            method: list
        contract_overview:
            route: /contract/{contract:int}
            use: API::ContractController:overview
        fulfill_contract:
            route: /contract/{contract:int}/fulfill
            use: API::ContractController:fulfill
            check: checkIsAuthenticated
            methods: [POST]