index:
    route: /
    controller: Common:TradeController
    method: list

trades:
    route: /trades
    controller: Common:TradeController
    method: list

trade_overview:
    route: /trade/{trade:int}
    controller: Common:TradeController
    method: overview

farmer_overview:
    route: /farmer/{farmer:text}
    controller: Common:FarmerController
    method: overview

heartbeat: 
    route: /heartbeat
    controller: SVXController
    method: heartbeat

login:
    route: /login
    controller: SecurityController
    method: login

register:
    route: /register
    controller: SecurityController
    method: register

logout:
    route: /logout
    controller: SecurityController
    method: logout

test:
    route: /test
    controller: SVXController
    method: test

search:
    route: /search
    controller: SVXController
    method: search

jobs:
    route: /jobs
    controller: JobController
    method: list



partners:
    type: group
    route: /partners
    routes: 
        list:
            route: ~
            controller: PartnerController
            method: list
        overview:
            route: /{partner:int}
            controller: PartnerController
            method: overview