index:
    route: /
    use: Common::TradeController:list

test:
    route: /test
    use: Common::SVXController:testAction

trades:
    route: /trades
    use: Common::TradeController:list

trade_overview:
    route: /trade/{trade:int}
    use: Common::TradeController:overview

farmer_overview:
    route: /farmer/{farmer:text}
    use: Common::FarmerController:overview

login:
    route: /login
    use: Common::SecurityController:login

register:
    route: /register
    use: Common::SecurityController:register

logout:
    route: /logout
    use: Common::SecurityController:logout

search:
    route: /search
    use: Common::SVXController:search

jobs:
    route: /jobs
    use: Common::JobController:list
    
partners:
    type: group
    route: /partners
    routes: 
        list:
            route: ~
            use: Common::PartnerController:list
        overview:
            route: /{partner:int}
            use: Common::PartnerController:overview