Farmer:
    table: farmers
    keys: [id]
    on_delete: cascade
    fields:
        id:
            column: unique_id_fixed
            type: text
        rawId:
            column: unique_id_raw
            type: text
        name:
            column: name
            type: text
        gold:
            column: gold
            type: int
        username:
            column: username
            type: text
        isAdmin:
            column: is_admin
            type: boolean
        createdAt:
            column: created_at
            type: timestamp
        modifiedAt:
            column: modified_at
            type: timestamp
        lastSync:
            column: last_sync
            type: timestamp
        trades:
            target_entity: Trade
            join:
                type: many
                local: id
                foreign: seller
                order_by: ['created_at', 'DESC']
        token:
            column: token
            type: text

Trade:
    table: trades
    keys: [id]
    on_delete: cascade
    fields:
        id:
            column: id
            type: serial
        status:
            column: status
            type: text
        seller:
            target_entity: Farmer
            column: seller
            join:
                type: one
                foreign: id
                local: seller
        buyer:
            target_entity: Farmer
            column: buyer
            join:
                type: one
                foreign: id
                local: buyer
        items:
            target_entity: TradeItem
            join:
                type: many
                foreign: trade
                local: id
        askingPrice:
            column: asking_price
            type: numeric
        title:
            column: title
            type: text
        createdAt:
            column: created_at
            type: timestamp
        modifiedAt:
            column: modified_at
            type: timestamp

TradeItem:
    table: trade_items
    keys: [id]
    fields:
        id:
            column: id
            type: serial
        trade:
            target_entity: Trade
            column: trade
            join:
                type: one
                foreign: id
                local: trade
        item: 
            column: item
            join:
                table: items
                type: one
                local: item
                foreign_column: id
                columns: [id,name,description,image_url]
        amount:
            column: amount
            type: int
        quality:
            column: quality
            type: int

Contract:
    table: contracts
    keys: [id]
    fields:
        id: 
            column: id
            type: serial
        title:
            column: title
            type: text
        description:
            column: description
            type: text
        owner: 
            target_entity: Partner
            column: owner
            join:
                type: one
                foreign: id
                local: owner
        totalOrders:
            column: total_orders
            type: int
        remainingOrders:
            column: remaining_orders
            type: int
        items:
            target_entity: ContractItem
            join:
                type: many
                foreign: contract
                local: id
        status:
            column: status
            type: text
        payout: 
            column: payout
            type: int
        createdAt:
            column: created_at
            type: timestamp
        modifiedAt:
            column: modified_at
            type: timestamp

ContractFulfillment:
    table: contract_fulfillments
    keys: [id]
    fields:
        id:
            column: id
            type: serial
        contract:
            target_entity: Contract
            column: contract
            join:
                type: one
                foreign: id
                local: contract
        farmer:
            target_entity: Farmer
            column: farmer
            join:
                type: one
                foreign: id
                local: farmer
        date:
            column: date
            type: timestamp

ContractItem:
    table: contract_items
    keys: [id]
    fields:
        id:
            column: id
            type: serial
        contract:
            target_entity: Contract
            column: contract
            join:
                type: one
                foreign: id
                local: contract
        item: 
            column: item
            join:
                table: items
                type: one
                local: item
                foreign_column: id
                columns: [id,name,description,image_url]
        quantity:
            column: amount
            type: int
        quality:
            column: quality
            type: int

Partner:
    table: partners
    keys: [id]
    fields:
        id: 
            column: id
            type: serial
        name:
            column: name
            type: text
        description:
            column: description
            type: text
        logo:
            column: logo
            type: text
        isApproved:
            column: is_approved
            type: boolean
            #default: false # todo
        isEnabled:
            column: is_enabled
            type: boolean
        contracts: 
            target_entity: Contract
            join:
                type: many
                local: id
                foreign: owner
                order_by: ['createdAt', 'DESC']
        createdAt:
            column: created_at
            type: timestamp
        modifiedAt:
            column: modified_at
            type: timestamp
