# =================
# ASSET ROUTES
# =================

javascript:
    route: /js/{filename:string}
    controller: Common:ResourceController
    method: getJS
    methods: [get, post]

style:
    route: /css/{filename:string}
    controller: Common:ResourceController
    method: getCSS
    methods: [get, post]

font:
    route: /font/{filename:string}
    controller: Common:ResourceController
    method: getFont
    methods: [get, post]

asset:
    route: /assets/{filename:string}
    controller: Common:ResourceController
    method: getAsset
    methods: [get, post]

logo:
    route: /assets/logos/{filename:string}
    controller: Common:ResourceController
    method: getAsset
    methods: [get, post]

favicon:
    route: /{filename:string}.ico
    controller: Common:ResourceController
    method: getAsset
    methods: [get, post]