# =================
# ASSET ROUTES
# =================

javascript:
    route: /js/{filename:string}
    use: Common::ResourceController:getJS
    methods: [get, post]

style:
    route: /css/{filename:string}
    use: Common::ResourceController:getCSS
    methods: [get, post]

font:
    route: /font/{filename:string}
    use: Common::ResourceController:getFont
    methods: [get, post]

asset:
    route: /assets/{filename:string}
    use: Common::ResourceController:getAsset
    methods: [get, post]

logo:
    route: /assets/logos/{filename:string}
    use: Common::ResourceController:getAsset
    methods: [get, post]

favicon:
    route: /{filename:string}.ico
    use: Common::ResourceController:getAsset
    methods: [get, post]