api:
    type: group
    route: /api
    routes: 
        sync:
            route: /sync
            controller: APIController
            method: sync
            methods: [get,post]
        new_trade:
            route: /trade/new
            controller: API:TradeController
            method: new
        trade_overview:
            route: /trade/{trade:int}/overview
            controller: API:TradeController
            method: overview
        farmer_overview:
            route: /farmer/{farmer:text}/overview
            controller: API:FarmerController
            method: overview
        farmers:
            route: /farmers
            controller: API:FarmerController
            method: getFarmers

partner:
    type: group
    route: /partners
    routes: 
        new_contract: 
            route: /{partner:int}/new_contract
            controller: Admin:PartnerController
            method: newContract
        edit: 
            route: /{partner:int}/edit
            controller: Admin:PartnerController
            method: newContract


